// Do not run this file. Enter, one-by-one, the following lines of code into REPL mode.

print("Hello, world);

print('Hello, world!');

let a = 5 + 3

let b = +5;

let 5 = 2;

print(5 ? 1 : 2);

print(1 + 2.0);

print(-"hello");

print(1 / 0);

print(name);

let c;
print(c);

if 1 { print("Condition was true"); }

"hello"(2);

fu greet(name) { print(format("Hello, ", name)); }
greet("Steve", "Jobs");

let d = print();

let e = "name".firstChar;

let f = {a: "A", b: "B"};
print(f.c);

let g = int("five");